#!/bin/bash

#mount -t 9p 127.0.0.1 /mnt/usbvm \
#     -oversion=9p2000.L,uname=root,access=any,aname=/mnt/dev/ath9k,trans=tcp,port=5640,dfltuid=0,dfltgid=0
echo manual >/mnt/usbvm/spectral_scan_ctl
echo trigger >/mnt/usbvm/spectral_scan_ctl
sleep 1s
cat /mnt/usbvm/spectral_scan0 >~/test.scan
ls -l ~/test.scan
