#!/bin/bash

BASEDIRS="$@"
amixer cset numid=3 1

declare -A seen
while [ 1 ]; do
for BASEDIR in $BASEDIRS; do
	pcap=`find  "$BASEDIR" | grep pcap | grep -v gz | tail -n1`
	if [ -z "$pcap" ]; then
		continue
	fi
	macs=`/usr/sbin/tcpdump -n -e -r $pcap | sed 's/[RS]A:/\nSA /' | grep 'SA '  | cut -f2 -d' ' | sort | uniq`
	for a in $macs; do
		if [ -z "${seen[$a]}" ]; then
			echo $a
			aplay /opt/owa/beep.wav >/dev/null 2>&1
		fi
		seen[$a]="t"
	done
done
sleep 2s
done
