#!/bin/bash

set -eo pipefail

DEV="$1"
if [ -z "$DEV" ]; then exit 1; fi

# this file is dumb but whatever
rm -f gps.time
while [ 1 ]; do
	grep -m1 "GPRMC" "${DEV}" >gps.time &
	gpspid=$!
	sleep 0.01s
	newv=`cat gps.time`
	if [ -z "$oldv" ]; then
		oldv=$newv
	elif [ -z "$newv" ]; then
		break
	fi
	wait $gpspid
	if [ -z "$oldv" ]; then
		oldv=`cat gps.time`
	fi
done
rm -f gps.time

# 095825.00 => 09:58:25
gpstime=`echo "$oldv" |  awk -v FS=, ' { print $2 } '`
gpshr=`echo "$gpstime" | sed 's/[0-9]./&\n/g;' | sed '1q;d'`
gpsmin=`echo "$gpstime" | sed 's/[0-9]./&\n/g;' | sed '2q;d'`
gpssec=`echo "$gpstime" | sed 's/[0-9]./&\n/g;' | sed '3q;d'`

# 181016 => October 18th, 2016
gpsdate=`echo "$oldv" | awk -v FS=, ' { print $10 } '`
gpsday=`echo "$gpsdate" | sed 's/[0-9]./&\n/g;' | sed '1q;d'`
gpsmon=`echo "$gpsdate" | sed 's/[0-9]./&\n/g;' | sed '2q;d'`
gpsyear=`echo "$gpsdate" | sed 's/[0-9]./&\n/g;' | sed '3q;d'`
gpsyear=`expr 2000 + $gpsyear`

#1970-01-01 00:00:00Z
datestr="${gpsyear}-${gpsmon}-${gpsday} ${gpshr}:${gpsmin}:${gpssec}Z"
echo $datestr

#date --set "${datestr}
#date --date='TZ="America/Los_Angeles" 09:00 next Fri'
